# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.7

# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - pytest --cov visitatie/

# Push the results back to codecov
after_success:
  - codecov --token="aac7e6c8-267d-46e6-a7b5-1f8364d09ca1"
