RESULT_DICT = {
    "Tako": {
        "naam": "Tako",
        "email": "tako.oefentherapie+tako@gmail.com",
        "Praktijkcode": "1110110",
        "Aantal Dossiers": "4",
        "Aantal Therapeuten": "2",
        "Bezoekende Praktijkcode": "1110112",
        "Door de juiste bezocht": "True",
        "Dossier per Therapeut": "2.0",
        "Regio": "Champions League",
        "door de juiste bezocht": "True",
        "Praktijktoets": "1.0",
        "Dossiertoets": "1.0",
        "twee meetinstrumenten": "1",
        "STarTBack": "1",
        "GPE": "1",
        "Catagorie": "Groen",
        "Score": "3",
    },
    "Real Madrid": {
        "naam": "Real Madrid",
        "email": "tako.oefentherapie+real@gmail.com",
        "Praktijkcode": "1110111",
        "Aantal Dossiers": "4",
        "Aantal Therapeuten": "2",
        "Bezoekende Praktijkcode": "1110112",
        "Door de juiste bezocht": "True",
        "Dossier per Therapeut": "1.0",
        "Regio": "Champions League",
        "door de juiste bezocht": "True",
        "Praktijktoets": "1.0",
        "Dossiertoets": "1.0",
        "twee meetinstrumenten": "1",
        "STarTBack": "1",
        "GPE": "0",
        "Catagorie": "Groen",
        "Score": "3",
    },
    "Barca": {
        "naam": "Barca",
        "email": "tako.oefentherapie+Barca@gmail.com",
        "Praktijkcode": "1110112",
        "Aantal Dossiers": "1",
        "Aantal Therapeuten": "1",
        "Bezoekende Praktijkcode": "1110112",
        "Door de juiste bezocht": "True",
        "Dossier per Therapeut": "1.0",
        "Regio": "Champions League",
        "door de juiste bezocht": "True",
        "Praktijktoets": "0.8",
        "Dossiertoets": "0.91",
        "twee meetinstrumenten": "0.95",
        "STarTBack": "1",
        "GPE": "1",
        "Catagorie": "Rood",
        "Score": "0",
    },
    "Fysiotherapiepraktijk Willemsstad": {
        "naam": "Fysiotherapiepraktijk Willemsstad",
        "email": "tako.oefentherapie+FysiotherapiepraktijkWillemsstad@gmail.com",
        "Praktijkcode": "1110212",
        "Aantal Dossiers": "1",
        "Aantal Therapeuten": "1",
        "Bezoekende Praktijkcode": "1110112",
        "Door de juiste bezocht": "True",
        "Dossier per Therapeut": "1.0",
        "Regio": "America",
        "door de juiste bezocht": "True",
        "Praktijktoets": "0.8",
        "Dossiertoets": "0.91",
        "twee meetinstrumenten": "0.95",
        "STarTBack": "1",
        "GPE": "1",
        "Catagorie": "Rood",
        "Score": "0",
    },
    "Praktijk Fysiotherapie NYC": {
        "naam": "Praktijk Fysiotherapie NYC",
        "email": "tako.oefentherapie+NYC@gmail.com",
        "Praktijkcode": "1110211",
        "Aantal Dossiers": "4",
        "Aantal Therapeuten": "2",
        "Bezoekende Praktijkcode": "1110112",
        "Door de juiste bezocht": "True",
        "Dossier per Therapeut": "1.0",
        "Regio": "Champions League",
        "door de juiste bezocht": "True",
        "Praktijktoets": "1.0",
        "Dossiertoets": "1.0",
        "twee meetinstrumenten": "1",
        "STarTBack": "1",
        "GPE": "0",
        "Catagorie": "Groen",
        "Score": "3",
    },
}
